BOOK_ALIASES = {
    # ===== English =====
    # Abbreviations → full names (keys lowercase)
    "gen": "Genesis",
    "exod": "Exodus",
    "lev": "Leviticus",
    "num": "Numbers",
    "deut": "Deuteronomy",
    "josh": "Joshua",
    "judg": "Judges",
    "ruth": "Ruth",
    "1sam": "1 Samuel",
    "2sam": "2 Samuel",
    "1kgs": "1 Kings",
    "2kgs": "2 Kings",
    "1chr": "1 Chronicles",
    "2chr": "2 Chronicles",
    "ezra": "Ezra",
    "neh": "Nehemiah",
    "esth": "Esther",
    "job": "Job",
    "ps": "Psalms",
    "prov": "Proverbs",
    "eccl": "Ecclesiastes",
    "song": "Song of Solomon",
    "isa": "Isaiah",
    "jer": "Jeremiah",
    "lam": "Lamentations",
    "ezek": "Ezekiel",
    "dan": "Daniel",
    "hos": "Hosea",
    "joel": "Joel",
    "amos": "Amos",
    "obad": "Obadiah",
    "jonah": "Jonah",
    "mic": "Micah",
    "nah": "Nahum",
    "hab": "Habakkuk",
    "zeph": "Zephaniah",
    "hag": "Haggai",
    "zech": "Zechariah",
    "mal": "Malachi",

    "matt": "Matthew",
    "mark": "Mark",
    "luke": "Luke",
    "john": "John",
    "acts": "Acts",
    "rom": "Romans",
    "1cor": "1 Corinthians",
    "2cor": "2 Corinthians",
    "gal": "Galatians",
    "eph": "Ephesians",
    "phil": "Philippians",
    "col": "Colossians",
    "1thess": "1 Thessalonians",
    "2thess": "2 Thessalonians",
    "1tim": "1 Timothy",
    "2tim": "2 Timothy",
    "titus": "Titus",
    "phlm": "Philemon",
    "heb": "Hebrews",
    "jas": "James",
    "1pet": "1 Peter",
    "2pet": "2 Peter",
    "1john": "1 John",
    "2john": "2 John",
    "3john": "3 John",
    "jude": "Jude",
    "rev": "Revelation",

    # Full names → full names (English keys lowercase)
    "genesis": "Genesis",
    "exodus": "Exodus",
    "leviticus": "Leviticus",
    "numbers": "Numbers",
    "deuteronomy": "Deuteronomy",
    "joshua": "Joshua",
    "judges": "Judges",
    "ruth": "Ruth",
    "1 samuel": "1 Samuel",
    "2 samuel": "2 Samuel",
    "1 kings": "1 Kings",
    "2 kings": "2 Kings",
    "1 chronicles": "1 Chronicles",
    "2 chronicles": "2 Chronicles",
    "ezra": "Ezra",
    "nehemiah": "Nehemiah",
    "esther": "Esther",
    "job": "Job",
    "psalms": "Psalms",
    "proverbs": "Proverbs",
    "ecclesiastes": "Ecclesiastes",
    "song of solomon": "Song of Solomon",
    "isaiah": "Isaiah",
    "jeremiah": "Jeremiah",
    "lamentations": "Lamentations",
    "ezekiel": "Ezekiel",
    "daniel": "Daniel",
    "hosea": "Hosea",
    "joel": "Joel",
    "amos": "Amos",
    "obadiah": "Obadiah",
    "jonah": "Jonah",
    "micah": "Micah",
    "nahum": "Nahum",
    "habakkuk": "Habakkuk",
    "zephaniah": "Zephaniah",
    "haggai": "Haggai",
    "zechariah": "Zechariah",
    "malachi": "Malachi",

    "matthew": "Matthew",
    "mark": "Mark",
    "luke": "Luke",
    "john": "John",
    "acts": "Acts",
    "romans": "Romans",
    "1 corinthians": "1 Corinthians",
    "2 corinthians": "2 Corinthians",
    "galatians": "Galatians",
    "ephesians": "Ephesians",
    "philippians": "Philippians",
    "colossians": "Colossians",
    "1 thessalonians": "1 Thessalonians",
    "2 thessalonians": "2 Thessalonians",
    "1 timothy": "1 Timothy",
    "2 timothy": "2 Timothy",
    "titus": "Titus",
    "philemon": "Philemon",
    "hebrews": "Hebrews",
    "james": "James",
    "1 peter": "1 Peter",
    "2 peter": "2 Peter",
    "1 john": "1 John",
    "2 john": "2 John",
    "3 john": "3 John",
    "jude": "Jude",
    "revelation": "Revelation",

    # ===== Korean =====
    # Common Korean abbreviations or names → full Korean book names
    "창": "창세기",
    "창세기": "창세기",
    "출": "출애굽기",
    "출애굽기": "출애굽기",
    "레": "레위기",
    "레위기": "레위기",
    "민": "민수기",
    "민수기": "민수기",
    "신": "신명기",
    "신명기": "신명기",
    "수": "여호수아",
    "여호수아": "여호수아",
    "삿": "사사기",
    "사사기": "사사기",
    "룻": "룻기",
    "룻기": "룻기",
    "삼상": "사무엘상",
    "사무엘상": "사무엘상",
    "삼하": "사무엘하",
    "사무엘하": "사무엘하",
    "왕상": "열왕기상",
    "열왕기상": "열왕기상",
    "왕하": "열왕기하",
    "열왕기하": "열왕기하",
    "대상": "역대상",
    "역대상": "역대상",
    "대하": "역대하",
    "역대하": "역대하",
    "스": "에스라",
    "에스라": "에스라",
    "느": "느헤미야",
    "느헤미야": "느헤미야",
    "에스": "에스더",
    "에스더": "에스더",
    "욥": "욥기",
    "욥기": "욥기",
    "시": "시편",
    "시편": "시편",
    "잠": "잠언",
    "잠언": "잠언",
    "전": "전도서",
    "전도서": "전도서",
    "아": "아가",
    "아가": "아가",
    "사": "이사야",
    "이사야": "이사야",
    "렘": "예레미야",
    "예레미야": "예레미야",
    "애": "예레미야애가",
    "예레미야애가": "예레미야애가",
    "겔": "에스겔",
    "에스겔": "에스겔",
    "단": "다니엘",
    "다니엘": "다니엘",
    "호": "호세아",
    "호세아": "호세아",
    "욜": "요엘",
    "요엘": "요엘",
    "암": "아모스",
    "아모스": "아모스",
    "옵": "오바댜",
    "오바댜": "오바댜",
    "욘": "요나",
    "요나": "요나",
    "미": "미가",
    "미가": "미가",
    "나훔": "나훔",
    "습": "하박국",
    "하박국": "하박국",
    "학": "스바냐",
    "스바냐": "스바냐",
    "학개": "학개",
    "스가랴": "스가랴",
    "말": "말라기",
    "말라기": "말라기",

    "마": "마태복음",
    "마태복음": "마태복음",
    "막": "마가복음",
    "마가복음": "마가복음",
    "눅": "누가복음",
    "누가복음": "누가복음",
    "요": "요한복음",
    "요한복음": "요한복음",
    "행": "사도행전",
    "사도행전": "사도행전",
    "롬": "로마서",
    "로마서": "로마서",
    "고전": "고린도전서",
    "고린도전서": "고린도전서",
    "고후": "고린도후서",
    "고린도후서": "고린도후서",
    "갈": "갈라디아서",
    "갈라디아서": "갈라디아서",
    "엡": "에베소서",
    "에베소서": "에베소서",
    "빌": "빌립보서",
    "빌립보서": "빌립보서",
    "골": "골로새서",
    "골로새서": "골로새서",
    "살전": "데살로니가전서",
    "데살로니가전서": "데살로니가전서",
    "살후": "데살로니가후서",
    "데살로니가후서": "데살로니가후서",
    "딤전": "디모데전서",
    "디모데전서": "디모데전서",
    "딤후": "디모데후서",
    "디모데후서": "디모데후서",
    "딛": "디도서",
    "디도서": "디도서",
    "몬": "빌레몬서",
    "빌레몬서": "빌레몬서",
    "히": "히브리서",
    "히브리서": "히브리서",
    "약": "야고보서",
    "야고보서": "야고보서",
    "벧전": "베드로전서",
    "베드로전서": "베드로전서",
    "벧후": "베드로후서",
    "베드로후서": "베드로후서",
    "요일": "요한1서",
    "요한1서": "요한1서",
    "요한2서": "요한2서",
    "요한3서": "요한3서",
    "유": "유다서",
    "유다서": "유다서",
    "계": "요한계시록",
    "요한계시록": "요한계시록",
}
